### ISSUE TITLE
Issues when using azd up/provision

### ISSUE THREAD

**Issue by jmatthiesen** [AzureCosmosDB/cosmosdb-nosql-copilot#41] opened 2024-10-22 21:39 UTC
I had a couple issues this morning when working with the infra via `azd up (or provision)`.

1. When starting AZD provision: The term 'Register-AzResourceProvider' is not recognized as a name of a cmdlet, function, script file, or executable | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    * This occurred when running locally in the terminal through VS Code. 
3. Then later I got this error: The PrincipalId 'd1fe6b28c19f44eea4b195a1232c307a' has type 'ServicePrincipal' , which is different from specified PrinciaplType 'User'.

#2 you can see in the logs from a workflow I'm trying to run to validate the sample for inclusion in an AZD gallery:

https://github.com/jmatthiesen/cosmosdb-nosql-copilot/actions/runs/11466248539/job/31906505349

**Comment by markjbrown** [comment] 2024-10-26 19:11
hi @jmatthiesen I don't see the error in the logs in your github action. I'm going to try a deployment and see if I can reproduce.

**Comment by markjbrown** [comment] 2024-10-27 12:08
I was not able to reproduce but I did take a look at the fix referenced here, https://github.com/Azure-Samples/azd-template-artifacts/blob/main/docs/development-guidelines/trouble-shooting.md#error-unmatchedprincipaltype-the-principalid-id-has-type-serviceprincipal--which-is-different-from-specified-princiapltype-user

The bicep for this sample already applies role assignments for both Cosmos and OpenAI for the current user. The change was for the user-assigned managed identity for OpenAI to change from servicePrincipal: None to ServicePrincipal.

Applied fix here, https://github.com/AzureCosmosDB/cosmosdb-nosql-copilot/pull/47

**Comment by markjbrown** [comment] 2024-10-27 12:08
Will close this issue for now. If this reoccurs, I'll take another look. Thanks.

**Closed by markjbrown** 2024-10-27 12:08 UTC
